// Типы Action'ов
export enum ActionType {     
  FETCH_CHATS = '@@chat/FETCH_CHATS',
  FETCH_CHATS_SUCCESS = '@@chat/FETCH_CHATS_SUCCESS',
  FETCH_CHATS_FAILED = '@@chat/FETCH_CHATS_FAILED',

  FETCH_MESSAGES = '@@chat/FETCH_MESSAGES',
  FETCH_MESSAGES_SUCCESS = '@@chat/FETCH_MESSAGES_SUCCESS',
  FETCH_MESSAGES_FAILED = '@@chat/FETCH_MESSAGES_FAILED',

  POST_MESSAGE = '@@chat/POST_MESSAGE',
  POST_MESSAGE_SUCCESS = '@@chat/POST_MESSAGE_SUCCESS',
  POST_MESSAGE_FAILED = '@@chat/POST_MESSAGE_FAILED',

  DELETE_MESSAGE = '@@chat/DELETE_MESSAGE',
  DELETE_MESSAGE_SUCCESS = '@@chat/DELETE_MESSAGE_SUCCESS',
  DELETE_MESSAGE_FAILED = '@@chat/DELETE_MESSAGE_FAILED',

  POST_CHAT = '@@chat/POST_CHAT',
  POST_CHAT_SUCCESS = '@@chat/POST_CHAT_SUCCESS',
  POST_CHAT_FAILED = '@@chat/POST_CHAT_FAILED',

  DELETE_CHAT = '@@chat/DELETE_CHAT',
  DELETE_CHAT_SUCCESS = '@@chat/DELETE_CHAT_SUCCES',
  DELETE_CHAT_FAILED = '@@chat/DELETE_CHAT_FAILED',

  ADD_INCOME_MESSAGE = '@@chat/ADD_INCOME_MESSAGE',
  RESET_INCOME_MESSAGES = '@@chat/RESET_INCOME_MESSAGES',
  
  FETCH_PROFILE = '@@profile/FETCH_PROFILE',
  FETCH_PROFILE_SUCCESS = '@@profile/FETCH_PROFILE_SUCCESS',
  FETCH_PROFILE_FAILED = '@@profile/FETCH_PROFILE_FAILED',

  POST_USER_NAME = '@@profile/POST_USER_NAME',
  POST_USER_NAME_SUCCESS = '@@profile/POST_USER_NAME_SUCCESS',
  POST_USER_NAME_FAILED = '@@profile/POST_USER_NAME_FAILED',
};
